services:
  ros-jazzy:
    image: osrf/ros:jazzy-desktop
    container_name: ros-jazzy
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
      - LANG=C.UTF-8
      - LC_ALL=C.UTF-8
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      - ${HOME}:/root
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /dev:/dev
      - ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}:${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    user: root
    working_dir: /root
    stdin_open: true
    tty: true


